dist: xenial
language: node_js
node_js:
- 4

# Uncomment me if this gets annoying
#
# notifications:
#   email: false

before_install:
  # try to get pill early, so configuration errors will be quickly caught
  - cd .travis
  - bash check-trailing-whitespace.sh
  - bash get-brass-pill.sh
  - cd ..
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip
  - sudo mv ninja /usr/bin/

install:
  # pwd: ~/urbit
  - pip3 install --user -I meson

script:
  - meson . ./build --buildtype=debugoptimized -Dgc=true -Dprof=true
  - cd ./build
  - ninja
  - ninja test
  - sudo ninja install
  - cd ../.travis
  - npm install
  - ulimit -c unlimited -S
  - npm run -s test; bash print-core-backtrace.sh $?

addons:
  apt:
    packages:
    - python3
    - python3-pip
    - python3-setuptools
    - python3-wheel
    - libgmp3-dev
    - libsigsegv-dev
    - openssl
    - libssl-dev
    - libncurses5-dev
    - gcc
    - libcurl4-gnutls-dev
    - unzip
    - gdb
# before_deploy: "make deb" # TODO
# deploy:
#   skip_cleanup: true
#   provider: releases
#   prerelease: true # turn this off for official releases
#   api_key:
#     secure: XX
#   file: ./build/urbit # TODO upload package from before_deploy
#   on:
#     repo: urbit/urbit
#     tags: true
